--[[
Title: Entity Animation Generator
Author(s): LiXizhi
Date: 2018/9/27
Desc: This is the character class generated by EntityAnimModel
It will try to follow the main player but will not leave the source AutoAnim block very far. 
When clicked, it will pop up a save as dialog
use the lib:
------------------------------------------------------------
NPL.load("(gl)script/apps/Aries/Creator/Game/Entity/EntityAnimCharacter.lua");
local EntityAnimCharacter = commonlib.gettable("MyCompany.Aries.Game.EntityManager.EntityAnimCharacter")
-------------------------------------------------------
]]
NPL.load("(gl)script/apps/Aries/Creator/Game/Entity/EntityNPC.lua");
NPL.load("(gl)script/apps/Aries/Creator/Game/Common/Files.lua");
local Files = commonlib.gettable("MyCompany.Aries.Game.Common.Files");
local EntityManager = commonlib.gettable("MyCompany.Aries.Game.EntityManager");
local Entity = commonlib.inherit(commonlib.gettable("MyCompany.Aries.Game.EntityManager.EntityNPC"), commonlib.gettable("MyCompany.Aries.Game.EntityManager.EntityAnimCharacter"));

-- class name
Entity.class_name = "EntityAnimCharacter";
EntityManager.RegisterEntityClass(Entity.class_name, Entity);
Entity.is_persistent = false;


function Entity:ctor()
	self:SetCanRandomMove(false);
	self:SetDummy(false);
end

-- set which anim model entity created this character
function Entity:SetAnimModelEntity(entity)
	self.animModelEntity = entity;
end

function Entity:GetAnimModelEntity()
	return self.animModelEntity;
end

-- called when the user clicks on the block
-- @return: return true if it is an action block and processed . 
function Entity:OnClick(x, y, z, mouse_button, entity, side)
	local filename = self:GetAnimModelEntity():GetFilename();
	local result = Files.ResolveFilePath(filename)
	local old_value = commonlib.Encoding.DefaultToUtf8(result.relativeToWorldPath or filename);

	NPL.load("(gl)script/apps/Aries/Creator/Game/GUI/OpenFileDialog.lua");
	local OpenFileDialog = commonlib.gettable("MyCompany.Aries.Game.GUI.OpenFileDialog");
	OpenFileDialog.ShowPage(L"输入新的文件名", function(result)
		if(result and result~="") then
			result = commonlib.Encoding.Utf8ToDefault(result);
			if(result~=old_value) then
				local filename = result;
				if(not filename:match("%.x$")) then
					filename = filename..".x";
				end
				self:SaveModelAs(filename)
			end
		end
	end, old_value, L"模型另存为", "model", true);

	return true;
end

-- @param filename: file relative to world directory
function Entity:SaveModelAs(filename, bForceOverwrite)
	local dest = GameLogic.GetWorldDirectory()..filename;
	if(ParaIO.DoesFileExist(dest, false) and not bForceOverwrite) then
		_guihelper.MessageBox(format(L"文件 %s 已经存在, 是否覆盖?", commonlib.Encoding.DefaultToUtf8(filename)), function(res)
			if(res and res == _guihelper.DialogResult.Yes) then
				self:SaveModelAs(filename, true)
			end
		end, _guihelper.MessageBoxButtons.YesNo);
	else
		ParaIO.CreateDirectory(dest);
		local src = self:GetAnimModelEntity():GetFilename();
		src = Files.GetWorldFilePath(src)
		if(src and ParaIO.CopyFile(src, dest, true)) then
			self:GetAnimModelEntity():SetFilename(filename);
			self:Say(L"保存成功", nil, true);
			GameLogic.AddBBS(nil, format(L"动画模型成功保存到%s", commonlib.Encoding.DefaultToUtf8(filename)));
		else
			GameLogic.AddBBS(nil, L"无法复制文件");
		end
	end
end

-- this will cause framemove to skip for this amount of time
function Entity:Wait(seconds)
	self.nextTickTime = commonlib.TimerManager.GetCurrentTime() + seconds*1000;
end

function Entity:ShallWait()
	return commonlib.TimerManager.GetCurrentTime() < (self.nextTickTime or 0);
end

-- called every frame
function Entity:FrameMove(deltaTime)
	Entity._super.FrameMove(self, deltaTime);

	if(not self:IsRemote()) then
		-- check respawn
		if(not self:ShallWait()) then
			local x,y,z = self:GetAnimModelEntity():GetBlockPos()
			local distSqToSrcBlock = self:DistanceSqTo(x,y,z);
			if(distSqToSrcBlock > 26*26) then
				self:SetBlockPos(x,y+1,z);
			elseif(distSqToSrcBlock > 16*16) then
				self:SetBlockTarget(x,y,z);
				self:Wait(5);
			else
				local px, py, pz = EntityManager.GetPlayer():GetBlockPos()
				local distSqToPlayer = self:DistanceSqTo(px, py, pz);
				if(distSqToPlayer > 10*10) then
					local x, y, z = self:GetRandomMovePos();
					self:MoveTo(x,y,z);
					self:Wait(1);
				elseif(distSqToPlayer > 4*4) then
					self:SetBlockTarget(px,py,pz);
					self:Wait(2);
				else
					local x, y, z = self:GetRandomMovePos();
					if(x) then
						self:MoveTo(x,y,z);
					end
					self:Wait(1);
				end
			end
		end
	end
end